# Generated by Django 6.1.1 on 2026-10-01 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('ecgains', models.CharField(max_length=50, unique=True)),
                ('agency_url', models.URLField()),
                ('container_selector', models.TextField()),
                ('bid_selector', models.TextField(blank=True)),
                ('due_date_selector', models.TextField(blank=True)),
                ('date_format', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('no_bid_phrase', models.CharField(blank=True, max_length=255)),
                ('fetch_mode', models.CharField(default='http', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('broken', models.BooleanField(default=True)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('last_status', models.CharField(choices=[('ACTIVE', 'Active'), ('NO_BID', 'No bid'), ('UNKNOWN', 'Unknown'), ('ERROR', 'Error')], default='UNKNOWN', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(unique=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_agencies', models.IntegerField(default=0)),
                ('active_agencies', models.IntegerField(default=0)),
                ('no_bid_agencies', models.IntegerField(default=0)),
                ('unknown_agencies', models.IntegerField(default=0)),
                ('error_agencies', models.IntegerField(default=0)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('NO_BID', 'No bid'), ('UNKNOWN', 'Unknown'), ('ERROR', 'Error')], max_length=20)),
                ('broken_at_check', models.BooleanField()),
                ('container_found', models.BooleanField(default=False)),
                ('entries_found', models.IntegerField(default=0)),
                ('dates_parsed', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitors.agencymonitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitors.monitorrun')),
            ],
        ),
    ]
