# Generated by Django 4.2.30 on 2026-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_alter_agencycheck_id_alter_agencymonitor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ecgains', models.CharField(max_length=50)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.TextField()),
                ('broken', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BidStatusRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spider_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('active_status', models.CharField(choices=[('ACTIVE', 'Active'), ('NO_BID', 'No bid'), ('UNKNOWN', 'Unknown'), ('ERROR', 'Error')], default='UNKNOWN', max_length=20)),
                ('repair_requested', models.BooleanField(default=False)),
                ('repair_requested_at', models.DateTimeField(blank=True, null=True)),
                ('repair_completed', models.BooleanField(default=False)),
                ('repaired_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bid_status',
                'managed': False,
            },
        ),
    ]
