# Generated by Django 4.2.30 on 2026-10-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0005_bidsource_bidstatusrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorrun',
            name='notification_sent',
        ),
        migrations.RemoveField(
            model_name='monitorrun',
            name='notification_sent_at',
        ),
    ]
