# Generated by Django 4.2.30 on 2026-10-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0006_remove_monitorrun_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorrun',
            name='run_date',
            field=models.DateField(),
        ),
    ]
